### PR TITLE
Add a C implementation

### PR DESCRIPTION
**Pull request by mpu**
Hey,

this should give you something to grind on!

### CODE REVIEW

**Comment by euantorano** [comment]
Nice, thanks. I'll give this a go tonight after work.

**Comment by mpu** [comment]
You can tweak `NWorkers` to be the number of cores available on your computer.

**Comment by euantorano** [comment]
Unfortunately this doesn't seem to work on my machine:

```[1]    39479 segmentation fault  ./C/fast ./ngrams.tsv 1 2```

The backtrace from gdb is as follows:

```
Starting program: /Users/euan/Desktop/faster-command-line-tools-in-nim/a.out ngrams.tsv 1 2
[New Thread 0x1403 of process 41730]
warning: unhandled dyld version (15)
[New Thread 0x1207 of process 41730]
[New Thread 0x1503 of process 41730]
[New Thread 0x1603 of process 41730]
[New Thread 0x1703 of process 41730]
[New Thread 0x1803 of process 41730]
[New Thread 0x1903 of process 41730]
[New Thread 0x1a03 of process 41730]
[New Thread 0x1b03 of process 41730]

Thread 3 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x1207 of process 41730]
0x00007fff99a14297 in ?? ()
(gdb) backtrace
#0  0x00007fff99a14297 in ?? ()
#1  0x000070000b1cfe90 in ?? ()
#2  0x0000000100000785 in addcount (b=0x180008ff,
    key=0x1303 <error: Cannot access memory at address 0x1303>, count=1)
    at C/fast.c:50
Backtrace stopped: frame did not save the PC
```

**Comment by mpu** [comment]
Duh, I think I know what's wrong...
The `realloc` calls have an invalid second argument.
There's also another bug that I knew of (triggered for instance when `NWorkers == 1`).
I'll fix those and make another pull request!

**Comment by euantorano** [comment]
Great, thanks. It'll probably be tomorrow night before I get another chance to look at it anyway :smile:

**Pull request merged**
