### PR TITLE
Make D code equivalent to Nim

### PR DESCRIPTION
**Pull request by Timbus**
I took some issue with how the D code looks compared to the Nim, especially when the D code can be made almost equivalent. I especially found the use of an external CSV parser library to be unfair.

As such I've refactored to code to be more in line with your example. It also happens to be faster, at least on LDC.

### CODE REVIEW

**Comment by euantorano** [comment]
I take it the fast cvs module is taken from here? https://github.com/quickfur/fastcsv

The Nim code exclusively uses the Nim standard library, not an “external CSV parser”, and I don’t personally see using the standard library as being unfair at all. The D code was taken from the original blog post on the D website - as somebody who doesn’t use D, I assumed it was idiomatic code since it was posted there. 

I’ll review this anyway and update the readme. I need to run the Nim version with Nim 0.18 anyway.

**Comment by Timbus** [comment]
Yes, the fast csv parser is from there, D has one in its stdlib, but it's pretty archaic+slow and fastcsv should replace it.
I'm aware the D code wasn't yours and I meant no disrespect by making this PR, I just felt like the syntax wasn't a fair apples-to-apples comparison when I looked at it. Some of the reason being that the original author made the code a little rough looking.. But also, his code manually handling the CSV parsing added a lot of extra noise.
Overall I think my changes make it a fair comparison.

**Comment by euantorano** [comment]
I'm about to take a look and see if I can improve the way we build and run everything, might end up emrging your changes in manually depending upon how it goes. Thanks for the update!

**Comment by euantorano** [comment]
Ok, I've made the changes I was discussing earlier, unfortunately this PR is now in a conflict state. Any chance you could clean it up @Timbus? The changes I've made should make it easier to run the different versions so long as you have Docker installed.

**Comment by Timbus** [comment]
Rebased it all to make it cleaner. Let me know if anything needs fixing.

**Comment by euantorano** [comment]
Great, thanks. I’ll merge later this morning.

**Comment by jondegenhardt** [comment]
Regarding the file format used in the original blog post - The examples used in the D blog post were chosen to illustrate certain techniques for improving performance applicable in many programming situations. Primarily regarding memory management and lazy programming. These techniques work in many programming languages, not just D.

Using a CSV parser in the examples would have made it difficult to illustrate these techniques, that's one reason one wasn't used.

For this reason, the file format chosen was a delimited file format that didn't use CSV escapes. This was not discussed explicitly in the blog post, but it was the intent. It's not actually correct to process such a delimited file using a CSV parser unless the parser supports turning off CSV escape syntax. (Otherwise the parser will incorrectly interpret unintended escape sequences.)

A performance consideration when comparing solutions is whether there is the assumption that the data can be read into memory all at once. This was not discussed in the blog post to keep the writing simple. However, the code in the blog post did not assume a file would fit into memory, and could have easily been changed to read from standard input or multiple files. However, when a file can be read entirely into memory all at once this will be significantly faster.

The Fast CSV parser differs from the code in the blog post on both counts. It assumes CSV escapes, and assumes the entire data can be read into memory all at once.

It is of course completely legitimate to make comparisons based on using CSV file format (with escapes), with the assumption the data can be read into memory all at once. Given that the code in the repo is being used for performance comparisons, it might be worth pointing out these assumptions in the readme.

**Comment by euantorano** [comment]
Great points Jon, thanks for weighing in. I’ll add something to the readme to explain that.

**Pull request merged**
